"""GENERATED by tools/extract_opcodes.py - opcodes reverse-engineered
from the official ZKTeco SDK. Do not edit by hand; values are factual
opcode numbers."""

OPCODES: dict[str, int] = {
    'DownloadPicture': 0x272d,
    'DownloadUserPhoto': 0x271a,
    'GetCapturePicByList': 0x271c,
    'GetDeviceInfo': 0x000b,
    'GetPhotoByName': 0x07de,
    'GetPhotoCount': 0x07dd,
    'GetPhotoNamesByTime': 0x07e0,
    'GetPicList': 0x271d,
    'GetUserFace': 0x0096,
    'GetUserGroup': 0x0015,
    'GetUserIDCard': 0x2744,
    'GetUserInfoEx': 0x0050,
    'GetUserTZs': 0x0017,
    'GetUserTmpEx': 0x0058,
    'GetUserVD': 0x2724,
    'GetUserVerifyStyle': 0x0050,
    'UploadPicture': 0x272b,
    'UploadTheme': 0x272a,
    'UploadUserPhoto': 0x2719,
}
