"""Regenerate src/openzk/opcodes.py by reverse-engineering the official ZKTeco SDK.

Usage:
    uv run --extra extract python tools/extract_opcodes.py /path/to/sdk-binary

The SDK binary is proprietary and is NEVER committed; this tool only reads opcode
numbers from a copy you supply. Only the generated opcodes.py (factual opcode
numbers) is committed. Each exported function encodes its opcode as an immediate
`mov dword ptr [esp+N], <imm>`; we disassemble and read that immediate.
"""
import re
import sys
from pathlib import Path

import capstone
import pefile

TARGET = re.compile(r"(Download|Upload|GetUser|GetPhoto|GetPic|GetCapture|GetUserFace|"
                    r"GetUserTmp|GetLog|GetOpLog|GetRTLog|GetData|GetDeviceData|"
                    r"GetSysOption|GetDeviceInfo)", re.I)


def extract(dll_path: str) -> dict[str, int]:
    pe = pefile.PE(dll_path, fast_load=True)
    pe.parse_data_directories([pefile.DIRECTORY_ENTRY["IMAGE_DIRECTORY_ENTRY_EXPORT"]])
    base = pe.OPTIONAL_HEADER.ImageBase
    img = pe.get_memory_mapped_image()
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_32)
    out: dict[str, int] = {}
    for sym in pe.DIRECTORY_ENTRY_EXPORT.symbols:
        if not sym.name:
            continue
        name = sym.name.decode()
        clean = re.sub(r"^_|@\d+$", "", name)
        clean = re.sub(r"^(?:SSR_)?Z_", "", clean)
        if not TARGET.search(clean):
            continue
        data = img[sym.address:sym.address + 220]
        for ins in md.disasm(data, base + sym.address):
            if ins.mnemonic in ("ret", "retn", "int3"):
                break
            # mov dword ptr [esp + N], <imm>  -> the command opcode
            m = re.match(r"dword ptr \[esp \+ (?:0x)?[0-9a-f]+\], (0x[0-9a-f]+)$", ins.op_str)
            if ins.mnemonic == "mov" and m:
                out[clean] = int(m.group(1), 16)
                break
    return out


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: extract_opcodes.py /path/to/sdk-binary", file=sys.stderr)
        return 2
    table = extract(sys.argv[1])
    header = (
        "GENERATED by tools/extract_opcodes.py - opcodes reverse-engineered\n"
        "from the official ZKTeco SDK. Do not edit by hand; values are factual\n"
        "opcode numbers."
    )
    lines = [f'"""{header}"""', "", "OPCODES: dict[str, int] = {"]
    for k in sorted(table):
        lines.append(f"    {k!r}: {table[k]:#06x},")
    lines.append("}")
    Path("src/openzk/opcodes.py").write_text("\n".join(lines) + "\n")
    print(f"wrote {len(table)} opcodes to src/openzk/opcodes.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
